name: spin
channels:
  - pytorch
  - pyg
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.8
  - pytorch==1.13.0
  - pandas=1.3.5
  - torchvision
  - torchaudio
  - wheel
  - pip:
      - torch_spatiotemporal==0.1.1
      - pyg>=2.0